---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: cresta-weather-app
  labels:
    app: api
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000